
Buckle up, here with start the journeyðŸš²
----------------------ready to use dataset--------------
Found already existing npy
shape of Xs_train:  (3610, 3, 256, 256)
shape of Ys_train:  (3610, 1, 256, 256)
shape of Xt_train:  (3610, 3, 256, 256)
shape of Yt_train:  (3610, 1, 256, 256)
--------------------------------------------------------------------
Number of source training examples: 2527
Number of source validation examples: 1083
Finally atleast train and valid source dataloader section works ðŸ˜Œ
--------------------------------------------------------------------
 Shape of Xt_train is:(3610, 3, 256, 256)
--------------------------------------------------------------------
Number of target training examples: 2527
Number of target validation examples: 1083
Finally atleast train and valid target dataloader section works ðŸ˜Œ
length of train source:158, lenth of train target is 158
length of validation source:68, lenth of validation target is 68
The model has 31,037,633 trainable parameters
----------------------Traning phase-----------------------------
  0%|                                                                                                                                                                 | 0/160 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/share/mastoc/projects/erasmus/pratichhya_sharma/DAoptim/DAoptim/main.py", line 163, in <module>
    main(net)
  File "/share/mastoc/projects/erasmus/pratichhya_sharma/DAoptim/DAoptim/main.py", line 107, in main
    train_loss, acc_mat = Train.train_epoch(net,optimizer, source_dataloader, target_dataloader)
  File "/share/mastoc/projects/erasmus/pratichhya_sharma/DAoptim/DAoptim/train.py", line 65, in train_epoch
    g_xt, f_g_xt = net(xt)  # target embedded data
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/mastoc/projects/erasmus/pratichhya_sharma/DAoptim/DAoptim/model/unet.py", line 70, in forward
    dec1 = self.decoder1(dec1)
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/share/projects/erasmus/pratichhya_sharma/app/lib/python3.9/site-packages/torch/nn/functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.78 GiB total capacity; 12.39 GiB already allocated; 2.69 MiB free; 12.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF